Corrected casting problem for singular/plural values and included UnitTests for the casting cases
cloudfoundry-incubator/multiapps pull request #180
Opened 2020-12-11 10:54 UTC by abdermendz

#### Description: 

#### Issue:

2020-12-11 14:04 UTC, radito3 requested changes
Import our eclipse_formatter.xml into your IDE and fix the formatting of the new code + revert the formatting changes to old code

2020-12-11 14:53 UTC, radoslav-d commented on multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/util/PropertiesUtil.java
>              return result;
Could be:
```
if (singleValue != null) {
    result.add((T) singleValue);
}
return result;
```

2020-12-14 14:46 UTC, radito3 commented on multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/resolvers/PlaceholderResolver.java
> +            throw new ContentException("Invalid type provided for " + plural
Now that the message is extracted in a constant, use it

2020-12-14 14:46 UTC, radito3 commented on multiapps-mta/src/main/java/org/cloudfoundry/multiapps/mta/util/PropertiesUtil.java
> +            return result;
No need for this line

2020-12-15 14:08 UTC, merged